---

- name: "Riavvio Server"
  delegate_to: "{{ inventory_hostname }}"
  remote_user: 
  raw: "sudo /usr/sbin/shutdown -r +1"

- name: "In Attesa del riavvio"
  pause: seconds=70

- name: "Check Server Up"
  local_action: raw nc -c "exit" {{ inventory_hostname }} 22 
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10

